### PR TITLE
Initial Changes - Unshare folder/ Repurpose Delete

### PR DESCRIPTION
**Pull request by dharanisakary**
Hi Jon/Ritesh,
Please review the changes for this task.

Thanks,
Dharani

### CODE REVIEW

**Comment by dharanisakary** [comment]
Hi Ritesh,

I have made changes to fix the issues - Multiple messages showing up on delete model when multiple models in a folder are shared, error in updating folder status, as discussed.

Please let me know for any other issues. 

Thanks,
Dharani

**Comment by riteshsamala** [comment]
These changes look good to me, thanks @dharanisakary 

We have one issue to sort out, that is the underscores ( instead of spaces ) in the accordion display code, which I will work on and push for your review

**Review by riteshsamala — APPROVED** [review]
Tested and looks good to me, thanks dharani

**Comment by jonwetzel** [comment]
I think this is good to go.  I'll merge it and we can update dragoon_prod and then I'll test it again.

**Review by jonwetzel — APPROVED** [review]
I think this is good to go. I'll merge it and we can update dragoon_prod and then I'll test it again.

**Pull request merged**
